import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import ErrorButton from '@/components/error-button/ErrorButton';
import SearchBlock from '@/components/search-block/SearchBlock';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Harry Potter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/favicon.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <ErrorButton />
        </div>
        <div className={styles.center}>
          <SearchBlock />
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const response = await fetch(
    'https://api.potterdb.com//v1/spells?page[size]=10&page[number]=1'
  );
  const data = await response.json();
  return {
    props: {
      spells: data,
    },
  };
}